### ISSUE TITLE
v10 Release Logistics

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/issue-tracking#101]
Populate checklist here

- [ ] Blog post on Medium - **Tue 4/2**
- [ ] Write Slack announcement - **Tue 4/2**
- [ ] Deprecate packages https://github.com/carbon-design-system/issue-tracking/issues/99 **Thu 3/28**
- [ ] Manual release `carbon-components` **Thu 3/28**
  - [ ] Add CHANGELOG to v10 tag **Thu 3/28**
- [ ] Manual release `carbon-components-react` **Thu 3/28**
  - [ ] Bump carbon components version **Thu 3/28**
  - [ ] Add CHANGELOG to v10 tag **Thu 3/28**
- [ ] Confirm that relevant Carbon channels are monitored with support - **Tue 4/2**
- [ ] Remove all references to "beta" on site **Thu 3/28**
- [x] Consistent references to "Carbon v10" on all site and communications **Thu 3/28**
- [ ] Change "next.cds..." to "www.cds..." **Thu 3/28**
- [x] Deploy "v9.cds..." 
- [ ] Update beta kit name **Thu 3/28**
- [ ] Update social media assets for V10 **Thu 3/28**
- [ ] "Known Issues" list **Thu 3/28**
- [ ] Add codepen links #1295 **Tues 4/2**

**Comment by alisonjoseph** [comment]
related, website checklist for launch https://github.com/carbon-design-system/carbon-website/issues/1294
