### ISSUE TITLE
Update social media assets for v10 launch

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/issue-tracking#103]
Twitter and Medium accounts are using v9 styles. We should update to reflect v10 aesthetic. 
Old assets here: https://ibm.box.com/s/4k4pnpn3y3k4t0c1rba6mkjw0xq9tdd4

![image](https://user-images.githubusercontent.com/11670886/54836421-2a4aeb80-4c92-11e9-8274-ae32de868242.png)

**Comment by laurenmrice** [comment]
V10 social media assets updated! 🎉

Assets will be stored here: https://ibm.ent.box.com/folder/75222992739
