### ISSUE TITLE
Create v1 and next routes for carbon-components-vue

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/issue-tracking#105]
In order to allow carbon-components-vue to evolve with the Carbon Design System and avoid CSS from one version bleeding through to another version, it is necessary to be able to publish to multiple routes. 

The following are suggested 
v1.vue.carbondesignsystem.com - (v1 built for Carbon 9)
vue.carbondesignsystem.com - (current, at the moment v1 soon to be v2) 
next.vue.carbondesignsystem.com - (next, at the moment v2 may soon start to look at Vue 3)

**Comment by joshblack** [comment]
cc @shinytoyrobots how should we incorporate this into the current sprint?

**Comment by lee-chase** [comment]
Still relevant.
