### ISSUE TITLE
Create New Carbon add-on for dotcom

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/issue-tracking#110]
Had a short discussion with @joshblack and wanted to jump start a new add-on package for some specific components for digital/dotcom.

Repo name: `carbon-addons-dotcom`
Location: https://github.com/IBM

**Comment by photodow** [comment]
This is done. I reached out to @joshblack for next steps.

https://github.com/IBM/carbon-addons-dotcom

**Comment by joshblack** [comment]
Submitted initial files PR: https://github.com/IBM/carbon-addons-dotcom/pull/1
