### ISSUE TITLE
Draft a proposal for what a Carbon "roll on/roll off" program would look like

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/issue-tracking#125]
> _This issue was created from the "New ideas to try" list in our October retro. Feel free to update the description and assignees if needed._

- [ ] Have developers from ECP come to Carbon for 6 weeks after Patterns, before joining their product team. Create ambassadorships for Carbon.

- [ ] End of year have a formal proposal of what that would look like.

**Comment by shinytoyrobots** [comment]
I'd actually update this to be two bullet points;

Proposal for short term (e.g. ECP designers and developers, ambassadorships, quarterly rotations) options.

Proposal for permanent options (e.g. how does someone "graduate" from Carbon to be a leader who enthusiastically facilitates Carbon in a product team as a designer or dev on a permanent basis)
