### ISSUE TITLE
Retro: Team events

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/issue-tracking#128]
> _This issue was created from the "New ideas to try" list in our October retro. Feel free to update the description and assignees if needed._

- [ ] Find fall activities can we do as a team. Happy hour and/or corn maze

**Comment by aagonzales** [comment]
https://www.sweetberryfarm.com/index.html
Closes November 10th

https://www.bartonhillfarms.com/fall-festival
Closes November 3rd
