### ISSUE TITLE
Retro: Code freeze

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/issue-tracking#129]
> _This issue was created from the "New ideas to try" list in our October retro. Feel free to update the description and assignees if needed._

Code freeze seemed too long for this release. Can we do a proper QA process this week?

- [ ] Merge the demo day, planning, and endgame QA into one week during endgame.

**Comment by joshblack** [comment]
Next steps for codefreeze are to follow a new branching model, this should help alleviate the PR backlog issue that we ran into 👍 

![image](https://user-images.githubusercontent.com/3901764/66762465-a6459480-ee6b-11e9-9df4-7d269231dab6.png)

**Comment by abbeyhrt** [comment]
@joshblack what does this mean for code freeze? Essentially, are we not going to have it anymore?

**Comment by joshblack** [comment]
@abbeyhrt the process will change to:

- On the start of code freeze, a release branch is cut that mirrors master
- Folks can always contribute to master
- The release branch is frozen, the only exception being bug fixes found in the release that are cherry-picked from master

**Comment by abbeyhrt** [comment]
Ah okay gotcha, thanks for clarifying!
