### ISSUE TITLE
Make demo day an Event Central event

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/issue-tracking#132]
> _This issue was created from the "New ideas to try" list in our October retro. Feel free to update the description and assignees if needed._

The past demo audience was only the direct Carbon team. Who do we need to include on the extended invite? How can we make this an event central even?

- [ ] Include a broader audience for demo day.
- [ ] Make demo an event central event.

**Comment by shinytoyrobots** [comment]
If we make it an Event Central event we don't have to worry about the invite list at all. :)

**Comment by joshblack** [comment]
Is there any chance we could still have a team-only one, and maybe have an event central put together by leadership that summarizes what has been done?

**Comment by abbeyhrt** [comment]
Not sure if this helps @joshblack but @jillianhowarth and I are planning on doing a team only mid-release demo day this cycle.

**Comment by joshblack** [comment]
Definitely helps, but I still think there is value in the one at the end, as well. It's nice being able to speak openly/honestly about the release

**Comment by abbeyhrt** [comment]
Does that not come from the retro?

**Comment by joshblack** [comment]
I think it happens as part of it, for sure. It's definitely a different mode of thinking in that it's reflective and based around improvement instead of us sharing work with each other and potentially commiserating haha
