### ISSUE TITLE
Are there formal standards for Carbon?

### ISSUE THREAD

**Issue by Freya-Aster-Amelia** [carbon-design-system/issue-tracking#135]
Since there are many ports for the Carbon Design System and there's a lot of documentation and tutorials on the main website, I was wondering, whether there's a formal specification to ensure consistency of Carbon across all implementations.

I ask this question, because I would guess it's beneficial to have a framework independent formalization, but also for the future as new frameworks might emerge, or porting Carbon to different (perhaps non web based) platforms.

Also, I'm know of the IBM Design Language, but as far as I'm aware there is no strict formalization (for example) between different components or objects.

Thank you

**Comment by tay1orjones** [comment]
Great question! The formal specification for all components is what's documented on carbondesignsystem.com. This covers all the various aspects of the components such as visual styling, behavior, and accessibility.

The aspects of the system currently maintained by our dedicated core team is everything in the `carbon` repo, which includes `@carbon/react`. Additionally we maintain `@carbon/web-components` and all the Carbon for IBM.com project repositories.

For community-maintained implementations such as svelte, angular, vue, react native, etc. we rely on the maintaining teams to ensure parity with the canonical react and web-component versions the core team maintains.
