### ISSUE TITLE
Change all blue non-link text on Carbon site to another color

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#14]
When users see blue text, they generally interpret it as "clickable."

We have a bunch of text (headers, etc.) in the Carbon site that is currently blue, but not a link. Can we change those values to dark grey or black?

**Comment by kuehndaniel** [comment]
> When users see blue text, they generally interpret it as "clickable."

From Josh: Do we have a study that we could reference when we make the PR in for the changes? Would love to preserve that context 👍

**Comment by aagonzales** [comment]
Where is this concern coming from? I think color in headers is acceptable (agreed it should never be used on body copy size if not a link). I would personal wait until we did a website redesign with Carbon X to change any styles, seems low priority.

**Comment by designertyler** [comment]
@aagonzales I agree about addressing it for the redesign and why it hasn't been a priority. This is was moved over to this repo from an [old issue ](https://github.ibm.com/carbon/issues/issues/897)in our private repo. It's something that @claycrenshaw has been championing.

**Comment by aagonzales** [comment]
Just play devils advocate here then by that logic shouldn't everything that's interactive be blue then? Which we don't do, ie links in the nav. 

I think its fine to remove the blue but I think the website h3 and h4 styles will need to be revisited to help distinguish them hierarchically better. Other wise they look to similar.

**Comment by claycrenshaw** [comment]
Well, that's not exactly the logic at play. . . so no. Trust me @aagonzales, I'm not making this stuff up :) Agreed about making sure that the H3 and H4 styles still express the hierarchy.

**Comment by alisonjoseph** [comment]
Agree with @aagonzales that any website design changes right now are low priority until a redesign is done. 

Going to close this for now and we can re-address during the redesign.
