### ISSUE TITLE
Research prep: Questions and outcomes

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#17]
**What do we want to learn from users?**
How they discover information?
How do they share it with OM or dev?
How is the info saved? Bookmarked?
Any other interactions with slack channel, website, github, sketch library?
How frequently do they reference the system and language?
When do they check for updates to a system or language?
How is Carbon different from Duo? (start and end with this question)
When do users need language vs system?
What are the use cases for the design language?
How do user view a system vs. language? Utility? Inspiration?
How easy is using the system today?
Does the language or system live up to what its promises or your expectations?
Difference between "digital" "product" "web" etc...

**What needs validation?**
Users need an easy way to navigate from system to language.
Users need a way to navigate from system to system.

**Comment by kuehndaniel** [comment]
issue discussion can be found here: https://github.ibm.com/carbon/issues/issues/889

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-addons-website #2](https://github.com/carbon-design-system/carbon-addons-website/issues/2) via [**ZenHub**](https://www.zenhub.com/)
