### ISSUE TITLE
Accessibility content for HIG

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#18]
Work with Bo Cambell to incorporate accessibility content in the HIG, included in carbon component sections, and the guideline guidelines.

Resources:
http://w3-03.ibm.com/able/devtest/quick/
https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html#Using
https://uxdesign.cc/designing-for-accessibility-is-not-that-hard-c04cc4779d94
Apple showing how they use their own accessibility guidance
https://www.apple.com/accessibility/
Material https://material.io/design/usability/accessibility.html#

**Comment by kuehndaniel** [comment]
Issue history can be found here: https://github.ibm.com/carbon/issues/issues/836

**Comment by claycrenshaw** [comment]
New content has been pushed to Gatsby.
