### ISSUE TITLE
Docs Edit: User Flow

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#21]
Edit User Flow HIG entry for style and content.

http://hig-review-1.stage1.mybluemix.net/your-product-on-ibm-cloud/user-flow

**Comment by claycrenshaw** [comment]
[User Flow-CC.md.zip](https://github.com/carbon-design-system/issue-tracking/files/2394298/User.Flow-CC.md.zip)
@alisonjoseph Revised copy for this page is attached. Please let me know how to proceed to get this pushed to the Internal site.

**Comment by alisonjoseph** [comment]
At this point would make sense to add any new content to the Gatsby site, to avoid having to do the work twice. 

You can add the markdown files in that repo and open a PR. 
https://github.com/carbon-design-system/carbon-website-gatsby/tree/master/src/content

How to add content wiki: https://github.com/carbon-design-system/carbon-website-gatsby/blob/master/CONTENT.md .

**Comment by claycrenshaw** [comment]
@alisonjoseph This content is internal-only. Does that matter in this case?

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #58](https://github.com/carbon-design-system/carbon-website-gatsby/issues/58) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chrisconnors-ibm** [comment]
@claycrenshaw did you look at  https://github.com/carbon-design-system/carbon-website-gatsby/blob/master/CONTENT.md ?

> If page is internal only make sure to add "internal": true to the navigation.json file for that item.

 `"your-product-on-ibm-cloud": {
    "title": "Your Product on IBM Cloud",
    "internal": true,
    "sub-nav": {
      "catalog-entry": {
        "title": "Catalog Entry"
      },`
