### ISSUE TITLE
Carbon Site Feedback Loop Overhaul

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#23]
Overhaul of the user feedback loop of the Carbon site. 

Opened by Clay (as an epic):

Hypothesis: A well-designed user feedback loop on the Carbon site will dramatically improve the Carbon team's ability to respond quickly and effectively to the needs of our users.

- As a Carbon user, I can quickly and easily provide feedback on any portion of the Carbon site, without going through the Github new ticket workflow.

- As a member of the Carbon team, I can easily see and address all user feedback coming from the site.

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #56](https://github.com/carbon-design-system/carbon-website-gatsby/issues/56) via [**ZenHub**](https://www.zenhub.com/)
