### ISSUE TITLE
Establish Editorial Backlog for Carbon Site / HIG

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#25]
Ongoing:

Synthesize existing HIG content lists into a single master backlog of topics to be added. Review regularly to establish relative priorities.

Sources:
- "Competitive" Audit : What are the other guys doing?
- Internal lists: J. Wilks outline, etc.
- Items in GH  backlog

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #57](https://github.com/carbon-design-system/carbon-website-gatsby/issues/57) via [**ZenHub**](https://www.zenhub.com/)
