### ISSUE TITLE
Color Swatch Component for Carbon Site

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#34]
We need a MD-friendly component which will display a solid color swatch at a specified size.

Ideally, the component will be directly linked to the Carbon palette via tokens. Also, would be good to be able to use tokens to specify the dimensions of the rectangle.

So, for example, if I could specify in my MD file that I need a (M) sized swatch of color (Blue-60), the code would generate a rectangle of a pre-specified size and the hex code that is officially linked to “Blue 60”

If the swatch needs to represent a color that falls outside our “official” tokenized palette, then I should be able to specify the color via hex code.

**Comment by claycrenshaw** [comment]
@alisonjoseph

**Comment by alisonjoseph** [comment]
Issue moved to [carbon-design-system/carbon-website #187](https://github.com/carbon-design-system/carbon-website/issues/187) via [**ZenHub**](https://www.zenhub.com/)
