### ISSUE TITLE
Need a way to stage WIP pages for internal feedback

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#35]
As a content creator, I need to be able to stage WIP pages of the site on a server so that I can share the work remotely and gather feedback before making a PR.

A good short-term contender might be pages.github.com
I have tried setting this up myself, but something is not working with the configuration.

**Comment by joshblack** [comment]
We could help out automate here, but ideally it'd be a part of [the pull request workflow](https://guides.github.com/introduction/flow/). From the article:

> Pull Requests initiate discussion about your commits. Because they're tightly integrated with the underlying Git repository, anyone can see exactly what changes would be merged if they accept your request.
>
> You can open a Pull Request at any point during the development process: when you have little or no code but want to share some screenshots or general ideas, when you're stuck and need help or advice, or when you're ready for someone to review your work.

So we could use Pull Requests for staging things that aren't quite done yet for early feedback, and have a bot automatically deploy changes to a preview URL for people to see.

**Comment by alisonjoseph** [comment]
Agree that it would be great to be able to automate it in to the PR workflow.

**Comment by alisonjoseph** [comment]
closing this since @tw15egan added support for Surge! Instructions here https://github.com/carbon-design-system/carbon-website/wiki/Deploy-testing-url-with-Surge
