### ISSUE TITLE
[Website Component] Recreate IBM Design Language "Do-Don't" component for Carbon site

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#39]
Need a custom component to reproduce the functionality of the [IBM Design Language](https://w3.ibm.com/design/language/elements/icons/) "Do-don't" component so that we can efficiently transfer content from one site to the other.

As implemented in MD on [IBM Design Language](https://ibm.biz/BdYu4E) site:

<DoDontSmall>
  <Do
    src="../media/pages/icons/sizing-correct-size-do.svg"
    caption="Do use the correct icon size with IBM Plex."
  ></Do>
  <Dont
    src="../media/pages/icons/sizing-correct-size-dont.svg"
    caption="Don’t alter icon sizes."
  ></Dont>
</DoDontSmall>

![image.png](https://images.zenhubusercontent.com/5ba146414b5806bc2be8c046/c1f199c7-0373-4828-b4d6-7afcc3e23d73)

**Comment by chrisconnors-ibm** [comment]
We want the current style of the [IBM Design Language](https://w3.ibm.com/design/language/elements/icons/) Do/Don't.

**Comment by aagonzales** [comment]
Designs are done.
