### ISSUE TITLE
Left nav gets wonky at narrow browser widths

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#40]
![Screen Shot 2018-10-16 at 10.06.25 AM.png](https://images.zenhubusercontent.com/5ba146414b5806bc2be8c046/e33ec2c6-46c1-4f6f-8d53-9e02a5ad85c5)

On Chrome

**Comment by aledavila** [comment]
Happens in Firefox for DA also but it doesn't happen to me.

**Comment by joshblack** [comment]
Should this be in the website repo? There is an issue template we can use to help get all the info for bug reports over at: https://github.com/carbon-design-system/carbon-website/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

Should be able to see it when creating a new issue on that repo in this switcher view:

![screen shot 2018-10-16 at 4 47 13 pm](https://user-images.githubusercontent.com/3901764/47049519-2c4cd380-d163-11e8-827c-10204b0a3471.png)

**Comment by asudoh** [comment]
Let's merge this to carbon-design-system/carbon-website#272 - @claycrenshaw Don't hesitate to speak up if the merger doesn't make sense. Thanks!
