### ISSUE TITLE
Create carbon-components-vue repository 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/issue-tracking#41]
- [x] Create `carbon-components-vue` repo under `carbon-design-system` org in public github. 
- [x] Add `.github` files
- [x] Add LICENSE
- [x] Add `package.json`
- [ ] Setup CI
- [ ] Work on 1.0 roadmap and timeline
  - What is scope of work being delivered?
  - Who are the code owners?
  - What level of support can be provided?

fyi @lee-chase

**Comment by joshblack** [comment]
Updated @alisonjoseph!

**Comment by joshblack** [comment]
Project is available at: https://github.com/carbon-design-system/carbon-components-vue
Current proposal for v1.0: https://ibm.box.com/s/mci98kgjstsuef8ui94qg2ymp0z2ge8d

**Comment by joshblack** [comment]
cc @lee-chase to confirm it's in a good spot to move forward 😄
