### ISSUE TITLE
Class name prefix decision & update prefix

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/issue-tracking#53]
- [ ] Update default prefix to `ibm--` (create new v10 branch?) (https://github.com/IBM/carbon-components/issues/1409)
- [ ] Documentation for migration/upgrade strategry for current users with `bx--`
- [x] Support for custom prefix in React (https://github.com/IBM/carbon-components-react/issues/1359)

_Notes from @wonilsuh_

> ## Detailed description
> 
> The current class name prefix `bx--` seems like a legacy name. As Carbon becomes the one design system for IBM, and as experimental components are being developed, should it be updated to something more current, such as `ibm--`?
> 
> ## Note
> 
> On the Northstar side, we would like to use Carbon components sooner than later too. And our adopter base makes it difficult to change class names - if the class name prefix can be updated even if it's not immediately used in the experimental components, the Northstar system can start using it to better align.

**Comment by stanislavgeorgiev** [comment]
What about a `duo--` prefix?

**Comment by joshblack** [comment]
@stanislavgeorgiev `duo` as a name doesn't exist anymore. The name itself just represented the updates to the IBM Design Language 👍

**Comment by stanislavgeorgiev** [comment]
thanks @joshblack

**Comment by joshblack** [comment]
Got this feedback on `ibm` as a prefix:

> It's one thing to have it on proprietary ui lib for ibm.com only and something else to have it on popular OSS project aim also at external users.

Definitely agreed with it, if we want external users then having `ibm` be the prefix is kind of confusing.

**Comment by wonilsuhibm** [comment]
how about `idl--` ? we still want to brand this as an IBM thing, but this prefix is not as direct as `ibm--`

**Comment by joshblack** [comment]
@wonilsuhibm I think whatever the new namesake ends up being will ultimately determine the prefix. Like in https://github.com/google/material-design-lite they do `.mdl-`

**Comment by alisonjoseph** [comment]
Based on that then I think we should wait to update the prefix until we know what the new name will be, to avoid changing anything twice.

**Comment by asudoh** [comment]
Refs IBM/carbon-components-react#1627.
