### ISSUE TITLE
Date Picker - experimental component (feedback from review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/issue-tracking#64]
- [ ] Use Sans for numbers across the board instead of Mono.
- [ ] Change weight of header (month) to 600 from 700.

**Comment by asudoh** [comment]
Refs [IBM/carbon-components#1749](https://github.com/IBM/carbon-components/issues/1749)

**Comment by asudoh** [comment]
Moved to: [IBM/carbon-components#1862](https://github.com/IBM/carbon-components/issues/1862)
