### ISSUE TITLE
Tooltip - experimental component (feedback from review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/issue-tracking#66]
- [ ] Need 16 px padding at the bottom of tooltip. Right now the buttons and links are too close to the bottom border.

**Comment by asudoh** [comment]
CC @aledavila - @laurenmrice can we assume it's about click-to-open tooltip, or is it something else? Thanks!

**Comment by aledavila** [comment]
@asudoh I am assuming it is
