### ISSUE TITLE
Date Picker - experimental component (feedback from review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/issue-tracking#67]
- [ ] Take off hover on calendar icon in input field. There should be no hover.

**Comment by asudoh** [comment]
CC @marijohannessen @alisonjoseph - Just in case they haven't noticed this issue yet.

**Comment by asudoh** [comment]
Refs IBM/carbon-components#1749

**Comment by asudoh** [comment]
Moved to: IBM/carbon-components#1862
