### ISSUE TITLE
Write article for Carbon X Release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/issue-tracking#68]
We've received some feedback that it's unclear what we're working on with respect to our roadmap and our Carbon X release. It would be awesome if we could put something up, whether external or internal, detailing what is going on in our Carbon X release so that folks know what we're working and can plan accordingly.

**Comment by claycrenshaw** [comment]
Hey @joshblack can you provide a little more context around where the feedback is coming from? Developers? Designers? Executives? Thanks!

**Comment by joshblack** [comment]
@claycrenshaw I believe at the time it was mostly developers 👍 Although I'm sure designers and offering managers are also curious about how this impacts their releases or offerings.
