### ISSUE TITLE
Create a visual demo of a product page being designed and developed using Carbon 

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#7]
An executive needs a visual way to understand what Carbon is and how it is used in an easily understood presentation.

For Oct 22 we need a timelapse video showing the build of a product page using Carbon. This could also serve as a before and after example.

Ty Tyner has a product landing page for VSI that could be an interesting option for this demo since they are in A/B testing and still have the files for the original design.

**Comment by shinytoyrobots** [comment]
The VSI page for this would be great.

It might be worth showing the (still in existence, I think) provisioning page on control.bluemix.net, and then compare versus the provisioning on www.bluemix.net.

I managed the development implementation of this.

Jeff Ng and Zeus Courtois on the Cloud Platform UI team under Tiffany Cross were both part of the development effort on this. They may be able to provide additional input, and Janelle Arita led the design effort from Ty Tyner's team. 

This work also won an IBM Eminence & Excellence award, so it's a good example all round to tout to executives.

**Comment by shinytoyrobots** [comment]
NB: The title says "a demo of a product page being **designed**". Is the focus the design side, as obviously a huge part of the benefit of the design system is the speed and consistency of development implementation. I don't know how best that would be implemented in video form, though.

**Comment by shinytoyrobots** [comment]
From meeting discussion on 9/17...

Create a 1-2 minute video showing the design and development of a product page (does **not** have to be a "real" product) utilizing Carbon, to demonstrate how it works.

**Comment by shinytoyrobots** [comment]
If done, primary Carbon work would be building a design that someone else has made (for a single page), and also need assistance on video editing.

**Comment by designertyler** [comment]
@shinytoyrobots @kuehndaniel Is this video demo still needed?

**Comment by jeoffw** [comment]
Superseded by https://github.com/carbon-design-system/carbon-website/issues/1175

**Comment by kuehndaniel** [comment]
see Jeoff's note. closing issue
