### ISSUE TITLE
Define other 3 color themes

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/issue-tracking#79]
IBM Design Language a set of predefined themes. So far we only have the one white theme. The themes are named after their main page background. 
- [x] White
- [x] Gray 10
- [x] Gray 90
- [x] Gray 100

**Comment by shixiedesign** [comment]
### Token values of different themes are here:
https://ibm.ent.box.com/notes/365968650341

**Comment by shixiedesign** [comment]
Done! Closing this issue. Ref https://github.com/IBM/carbon-elements/issues/53 for details. 
https://ibm.ent.box.com/notes/365968650341
