### ISSUE TITLE
Update Slack channel descriptions

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/issue-tracking#87]
Update the Slack channel descriptions and purposed so that a user can easily know what each channel is for and where they should post their comment. 

- carbon-design-system
- carbon-elements
- carbon-components
- carbon-react
- carbon-vue
- carbon-spec

Add descriptions to [website](https://next.carbondesignsystem.com/help/support/#slack-channels) support page as well.

---------------------

Description at top of slack channel:

![image](https://user-images.githubusercontent.com/11670886/53187476-d7194680-35c8-11e9-9b05-411f3f3e3369.png)

Purpose inside the info icon in channel:

![image](https://user-images.githubusercontent.com/11670886/53187514-edbf9d80-35c8-11e9-852f-6d18947b1c4f.png)

**Comment by connor-leech** [comment]
Still need to do this. Don't delete!

**Comment by connor-leech** [comment]
Still needs to happen...
