### ISSUE TITLE
Carbon Outreach: Build email distro list

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#93]
Email is an important and effective channel for outreach to Carbon users and potential Carbon users. Not only can we use the email list to distribute info about updates to Carbon, etc., (Newsletter style) but we can also use this list for things like surveys to better understand our users.

- [ ] Collect known user emails from Slack channels, github, and other established channels
- [ ] Make a plan for continuous collection of emails over time
- [ ] Integrate list with an email service such as Mailchimp or whatever is preferred at IBM

*Thoughts*
Might make sense to keep track of known users vs. potential users, to cater messaging to those different audiences (more technical info vs. more marketing info)

**Comment by joshblack** [comment]
I think we'll need this to be opt-in, right? Might be worth piggybacking on the newsletter idea because of that.
