### ISSUE TITLE
Content: Link Common Actions in Glossary to Patterns

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#97]
The Carbon glossary (https://next.carbondesignsystem.com/guidelines/content/glossary) contains definitions for common UI actions.

Many of those actions are laid out in more detail in the Patterns section of the site (https://next.carbondesignsystem.com/patterns/common-actions)

Action needed: In the Glossary, link the actions to their description on the Common Actions page of Patterns wherever possible.

@connor-leech

**Comment by connor-leech** [comment]
Took care of this in #1197
