### ISSUE TITLE
Deprecate packages for v10

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/issue-tracking#99]
We are deprecating two packages in preference of upstream versions in Carbon Elements. This issue is to track updating the repo README to include the deprecation notice and linking to migration guides, alongside deprecating the packages themselves.

- [ ] `carbon-icons`
  - [ ] Update repo README https://github.com/IBM/carbon-icons/pull/99
  - [ ] Deprecate npm package
  - [ ] Archive repo
- [ ] `carbon-themes`
  - [ ] Update repo README https://github.com/carbon-design-system/carbon-themes/pull/38
  - [ ] Deprecate npm package
  - [ ] Archive repo

**Comment by shinytoyrobots** [comment]
This is a task specific to do today on release, yes?
